image: python:3.5


cache:
  paths:
    - .

test:
    script:
    - apt-get -y install python-pip
    - pip2 install six console
    - pip3 install six console
    - python2.7 test_base_suite.py
    - python3.5 test_base_suite.py
