version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: apt-get -y install python-pip
      - run: pip2 install six console
      - run: pip3 install six console
      - run: python2.7 test_base_suite.py
      - run: python3.5 test_base_suite.py
